const projectsData = [
  {
    title: "It's Weather!",
    bgColor: "#c9c8bc",
    color1: "#a6b7cc",
    color2: "#f2d8aa",
    image: "/images/screenshot-itsweather.png",
    description: "Weather application developed as part of my personal portfolio. It provides accurate and up-to-date weather information for users.",
    githubLink: "https://github.com/nandodani/ItsWeather",
    externalLink: "https://its-weather.vercel.app/",
    techStack: ["HTML5", "CSS3", "JavaScript", "React.js", "Node.js"],
  },
  {
    title: "SmartOwl",
    bgColor: "#8e80ec",
    color1: "#6e00ff",
    color2: "#ffcb2b",
    image: "/images/screenshot-smartowl.png",
    academicProject: true,
    description: "Final project of my degree: Productivity platform designed and developed to be your browser's homepage",
    githubLink: "https://github.com/nandodani/SmartOwl",
    externalLink: "",
    techStack: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React.js",
      "Node.js",
      "Bootstrap",
      "Firebase",
    ],
  },
  {
    title: "Portfolio",
    bgColor: "#f9ecfd",
    color1: "#eeeefb",
    color2: "#ecf1e4",
    image: "/images/screenshot-portfolio.png",
    description: "My website all developed by me. You can find the source code on my GitHub.",
    githubLink: "https://github.com/nandodani/nandodani.github.io/tree/main",
    externalLink: "",
    techStack: ["HTML5", "CSS3", "JavaScript", "React.js", "Node.js"],
  },
  {
    title: "2GamerGuys",
    bgColor: "#f4a000",
    color1: "#262626",
    color2: "#262626",
    image: "/images/screenshot-2gamerguys.png",
    academicProject: true,
    description: 'Project to "Programming III" curricular unit of my degree: Platform to manage your favorite games.',
    githubLink: "https://github.com/nandodani/2GamerGuys",
    externalLink: "",
    techStack: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React.js",
      "Bootstrap",
      "Node.js",
    ],
  },
  {
    title: "Streamflix",
    bgColor: "#1b262c",
    color1: "#3282b8",
    color2: "#0f4c75",
    image: "/images/screenshot-streamflix.png",
    academicProject: true,
    description: 'Project to "Programming II" curricular unit of my degree: Platform to manage your favorite movies and tv shows.',
    githubLink: "https://github.com/nandodani/streamflix",
    externalLink: "",
    techStack: ["HTML5", "CSS3", "JavaScript", "React.js", "Node.js"],
  },
];

export default projectsData;
